### ISSUE TITLE
Promotion of OSM

### ISSUE THREAD

**Issue by jwitcoski** [mvexel/ama#4]
One of the OSMF responsibilities is; Ensures OSM is promoted and shown off at full potential. 

Openstreetmap has no visibility in comparison to other web maps. A simple google trend shows it is non-existent in the eyes of the internet.  Do you think this is good? bad? how can you get someone to use it instead of a commercial provider? 
![openstreetmapstrends](https://cloud.githubusercontent.com/assets/5134087/11505456/6c99cccc-9818-11e5-958b-6330e32e6c11.JPG)
https://www.google.com/trends/explore#q=openstreetmap%2C%20mapquest%2C%20google%20maps%2C%20bing%20maps&cmpt=q&tz=Etc%2FGMT%2B5

**Comment by mvexel** [comment]
Again a great question. First off, Google / Bing / MapQuest are not similar to OSM and shouldn't be directly compared. And I am not even talking about open vs. closed. The commercial services are mapping application platforms as well as end user applications. OSM is something else altogether. OSM is free and open data powered by over 2 million people all around the world. That is how we should be known. 

(I think the web site currently does not represent that well enough. To my mind it should be more like [Show Me The Way](https://osmlab.github.io/show-me-the-way/) or [OSM live](http://live.openstreetmap.fr), with communication / QA / analysis tools for mappers underneath. The way the site is now reinforces the perception that we are much more like Bing / Google / MapQuest than we actually are.)

Back on topic. The fact that OSM is data creates a space for third parties to develop applications and services that do compete with Google / Bing / MapQuest (or even power them as of recently). This is all good and great things have come out of this co-existence. But OSM runs a real risk of having its own narrative of a dedicated community creating free and open data for all appropriated by these third parties. That is not good. OSM should own this narrative. This is important for two important reasons. First of all, the community needs to be able to identify itself with the project. Second of all, a healthy fundraising campaign and thus the sustainability of our financial situation depends on it.

So to conclude. I don't care so much about our google search trend line. I do care very much about the independence of OSM. That is why we need to invest in this.
